In [2]:
import numpy as np

In [3]:
arr = np.arange(0,11)

In [4]:
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [5]:
arr[8]

8

In [6]:
arr[1:5]

array([1, 2, 3, 4])

In [7]:
arr[:5]

array([0, 1, 2, 3, 4])

In [8]:
arr[3:]

array([ 3,  4,  5,  6,  7,  8,  9, 10])

In [9]:
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [21]:
arr[0:5] = 100
arr

array([100, 100, 100, 100, 100,   5,   6,   7,   8,   9,  10])

In [22]:
arr = np.arange(0,11)

In [23]:
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [28]:
slice_of_arr = arr[0:6]

In [27]:
slice_of_arr

array([0, 1, 2, 3, 4, 5])

In [29]:
slice_of_arr

array([0, 1, 2, 3, 4, 5])

In [30]:
slice_of_arr[:] = 99

In [31]:
slice_of_arr

array([99, 99, 99, 99, 99, 99])

In [32]:
arr

array([99, 99, 99, 99, 99, 99,  6,  7,  8,  9, 10])

In [33]:
arr_copy = arr.copy()

In [34]:
arr

array([99, 99, 99, 99, 99, 99,  6,  7,  8,  9, 10])

In [35]:
 arr_copy[:] = 200

In [36]:
arr_copy

array([200, 200, 200, 200, 200, 200, 200, 200, 200, 200, 200])

In [37]:
arr

array([99, 99, 99, 99, 99, 99,  6,  7,  8,  9, 10])

In [38]:
# matrix indexing mat[row, col]
#                 mat[row][col]

In [40]:
mat = np.array([[5,10,15],[20,25,30],[35,40,45]])

In [41]:
mat

array([[ 5, 10, 15],
       [20, 25, 30],
       [35, 40, 45]])

In [42]:
mat[0]

array([ 5, 10, 15])

In [43]:
mat[2]

array([35, 40, 45])

In [44]:
mat

array([[ 5, 10, 15],
       [20, 25, 30],
       [35, 40, 45]])

In [45]:
mat[1][1]

25

In [46]:
mat[1,1]

25

In [47]:
mat

array([[ 5, 10, 15],
       [20, 25, 30],
       [35, 40, 45]])

In [49]:
mat[0,2]

15

In [51]:
mat

array([[ 5, 10, 15],
       [20, 25, 30],
       [35, 40, 45]])

In [52]:
mat[:2,1:]

array([[10, 15],
       [25, 30]])

In [53]:
mat[1:,:2]

array([[20, 25],
       [35, 40]])

In [54]:
# Conditional Selection

In [57]:
arr = np.arange(1,11)
arr

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [58]:
arr > 4

array([False, False, False, False,  True,  True,  True,  True,  True,
        True])

In [59]:
bool_arr = arr > 4 # step 1 

In [60]:
arr[bool_arr] # step 2

array([ 5,  6,  7,  8,  9, 10])

In [61]:
arr[arr>4] # 1 step to get same result

array([ 5,  6,  7,  8,  9, 10])