In [1]:
import numpy as np

In [4]:
# Creating Numpy Array
my_list= [1,2,3]

In [5]:
np.array(my_list)

array([1, 2, 3])

In [7]:
my_matrix = [[1,2,3],[4,5,6],[7,8,9]]

In [8]:
np.array(my_matrix)

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [9]:
list(range(0,5))

[0, 1, 2, 3, 4]

In [10]:
np.arange(0,5)

array([0, 1, 2, 3, 4])

In [12]:
np.arange(0,11,2) # even start 0, odd start 1

array([ 0,  2,  4,  6,  8, 10])

In [14]:
np.zeros(3)

array([0., 0., 0.])

In [15]:
type(1)

int

In [17]:
np.zeros((3,5))

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

In [18]:
np.ones(4)

array([1., 1., 1., 1.])

In [19]:
np.ones((3,4))

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [22]:
np.linspace(0,10,51)

array([ 0. ,  0.2,  0.4,  0.6,  0.8,  1. ,  1.2,  1.4,  1.6,  1.8,  2. ,
        2.2,  2.4,  2.6,  2.8,  3. ,  3.2,  3.4,  3.6,  3.8,  4. ,  4.2,
        4.4,  4.6,  4.8,  5. ,  5.2,  5.4,  5.6,  5.8,  6. ,  6.2,  6.4,
        6.6,  6.8,  7. ,  7.2,  7.4,  7.6,  7.8,  8. ,  8.2,  8.4,  8.6,
        8.8,  9. ,  9.2,  9.4,  9.6,  9.8, 10. ])

In [23]:
np.eye(4)

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

In [25]:
np.random.rand(1)

array([0.68200667])

In [27]:
np.random.rand(3,5)

array([[0.65925352, 0.14324506, 0.54743277, 0.9419782 , 0.35094588],
       [0.70078655, 0.99269554, 0.20947785, 0.9535241 , 0.79476089],
       [0.42835266, 0.35729401, 0.53683982, 0.92596235, 0.00293288]])

In [29]:
np.random.randn(5,4)

array([[ 0.30329737,  0.3801809 , -0.2287411 ,  1.18055821],
       [-1.12233999, -1.38503213, -0.10681606, -0.81356366],
       [-0.09293656, -1.25991587, -2.72235523, -0.32656081],
       [-1.7747056 , -1.59481882, -1.00868705, -0.58477458],
       [ 0.56210337,  0.43241194,  0.21515811, -1.02225692]])

In [33]:
np.random.randint(1,100,10)

array([77, 10,  2, 43,  2, 31, 87,  3, 33, 23])

In [34]:
arr = np.arange(25)
ranarr = np.random.randint(0,50,10)

In [35]:
ranarr

array([ 3, 26, 25, 26, 35,  4, 30, 41, 28, 49])

In [36]:
arr.reshape(5,5)

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24]])

In [38]:
arr.reshape(5,5).shape

(5, 5)

In [39]:
arr.dtype

dtype('int32')

In [40]:
ranarr

array([ 3, 26, 25, 26, 35,  4, 30, 41, 28, 49])

In [41]:
ranarr.max()

49

In [46]:
ranarr.argmax()

9

In [47]:
ranarr

array([ 3, 26, 25, 26, 35,  4, 30, 41, 28, 49])

In [48]:
ranarr.min()

3

In [49]:
ranarr.argmin()

0